Changes for Autodesk
ApptuitAI/xcollector pull request #2
Opened 2017-08-14 12:27 UTC by phakudi

1) Added collectors for memcache, nginx & tomcat.
2) Fixed an issue with log format string in tcollector.py

2017-08-16 08:35 UTC, phakudi commented
@talonx I have re-opened it now, can you please review?

2017-08-17 12:06 UTC, talonx commented on collectors/etc/grok_exporter_conf.py
> +]
Will we be changing the existing Ansible task so that it changes this to include the opentsdb and tcollector ymls for the TSD nodes?

2017-08-17 12:17 UTC, talonx requested changes
1. Should we be committing the grok exporter binary? Can we fetch from github.com/grok../releases and inject our changes during the xcollector build process?

2. Should the location be /opt or /usr/local? All other agents (dynatrace, coscale) seem to install in /opt

3. For configuration (e.g. TSD host/port, auth token), should we have a config file (json, yaml, properties etc) that is not part of the xcollector? This will be part of the installation/onboarding process. Thoughts?

2017-08-18 06:42 UTC, phakudi commented on collectors/etc/grok_exporter_conf.py
> +]
Yes! We should. I can up that change.

2017-08-29 04:27 UTC, talonx approved these changes

2017-08-29 04:27 UTC, talonx commented
Looks good to me, we can merge.

2017-08-29 04:28 UTC, merged